//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSA_DBF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classificacao
    {
        public int Id { get; set; }
        public string nome { get; set; }
        public Nullable<int> id_aluno { get; set; }
        public Nullable<int> id_uc { get; set; }
        public Nullable<int> id_epoca { get; set; }
        public Nullable<int> nota { get; set; }
        public string obs { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual Epoca Epoca { get; set; }
        public virtual UC UC { get; set; }
    }
}
